openapi: "3.0.2"
info:
  title: Products
  version: "1.0"

components:
  schemas:
    product:
      description: Product
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        date1:
          type: string
          format: date
          example: "2020-06-25"
        date2:
          type: string
          format: date-time
          example: "2020-07-25T12:34:56Z"

paths:
  /:
    get:
      responses:
        "200":
          description: OK response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product"
